// This file has been generated by FeGen based on a spring application. Do not edit it.

import { ApiNavigationLink, ApiBase } from 'fegen-runtime';

/**
 * This type is used as a basis for the different variants of this domain type. It can be created in the frontend
 * (in order to store it to the backend, for example) as it does neither have mandatory `_links` nor `id`.
 */
export interface UserBase extends ApiBase {
    street: string
    
    _links?: {
        self: ApiNavigationLink
        
    }
}

/**
 * This type is used for data transfer. Each time we read an object of this domain type from a rest service,
 * this type will be returned.
 */
export interface UserDto extends UserBase {
    _links: {
        self: ApiNavigationLink
        
    }
}

/**
 * This type is the default type of choice in the frontend as it has an id (which can be added to the `UserDto`
 * via `apiHelper#getObjectId`). Consequently, this type is used for fields that reference this type.
 */
export interface User extends UserDto {
    id: number
}

export interface UserBaseProjection extends User {
    name: string
}