// This file has been generated by FeGen based on a spring application. Do not edit it.

import { ApiNavigationLink, ApiBase } from '@materna-se/fegen-runtime';

/**
 * This type is used as a basis for the different variants of this domain type. It can be created in the frontend
 * (in order to store it to the backend, for example) as it does neither have mandatory `_links` nor `id`.
 */
export interface AddressBase extends ApiBase {
    city: string
    country: string | null
    street: string
    zip: string
    
    _links?: {
        self: ApiNavigationLink
        
    }
}

/**
 * This type is used for data transfer. Each time we read an object of this domain type from a rest service,
 * this type will be returned.
 */
export interface AddressDto extends AddressBase {
    _links: {
        self: ApiNavigationLink
        
    }
}

/**
 * This type is the default type of choice in the frontend as it has an id (which can be added to the `AddressDto`
 * via `apiHelper#getObjectId`). Consequently, this type is used for fields that reference this type.
 */
export interface Address extends AddressDto {
    id: number
}

/**
 * This type is used as a basis for the different variants of this domain type. It can be created in the frontend
 * (in order to store it to the backend, for example) as it does neither have mandatory `_links` nor `id`.
 */
export interface ContactBase extends ApiBase {
    firstName: string
    lastName: string
    number: string | null
    address: Address | null
    owner: User | null
    _links?: {
        self: ApiNavigationLink
        address: ApiNavigationLink
        owner: ApiNavigationLink
    }
}

/**
 * This type is used for data transfer. Each time we read an object of this domain type from a rest service,
 * this type will be returned.
 */
export interface ContactDto extends ContactBase {
    _links: {
        self: ApiNavigationLink
        address: ApiNavigationLink
        owner: ApiNavigationLink
    }
}

/**
 * This type is the default type of choice in the frontend as it has an id (which can be added to the `ContactDto`
 * via `apiHelper#getObjectId`). Consequently, this type is used for fields that reference this type.
 */
export interface Contact extends ContactDto {
    id: number
}

/**
 * This type is used as a basis for the different variants of this domain type. It can be created in the frontend
 * (in order to store it to the backend, for example) as it does neither have mandatory `_links` nor `id`.
 */
export interface PrimitiveTestEntityBase extends ApiBase {
    booleanTrue: boolean
    date2000_6_12: string
    dateTime2000_1_1_12_30: string | null
    int32: number
    intMinusBillion: number
    long64: number
    optionalIntBillion: number | null
    optionalIntNull: number | null
    stringText: string
    
    _links?: {
        self: ApiNavigationLink
        
    }
}

/**
 * This type is used for data transfer. Each time we read an object of this domain type from a rest service,
 * this type will be returned.
 */
export interface PrimitiveTestEntityDto extends PrimitiveTestEntityBase {
    _links: {
        self: ApiNavigationLink
        
    }
}

/**
 * This type is the default type of choice in the frontend as it has an id (which can be added to the `PrimitiveTestEntityDto`
 * via `apiHelper#getObjectId`). Consequently, this type is used for fields that reference this type.
 */
export interface PrimitiveTestEntity extends PrimitiveTestEntityDto {
    id: number
}

/**
 * This type is used as a basis for the different variants of this domain type. It can be created in the frontend
 * (in order to store it to the backend, for example) as it does neither have mandatory `_links` nor `id`.
 */
export interface RelTestEntityBase extends ApiBase {
    testString: string
    embedded: EmbeddableTestEntity | null
    embeddedNullable: OtherEmbeddableTestEntity | null
    manyToMany: User[]
    manyToOneOptional: User | null
    manyToOneRequired: User
    oneToMany: User[]
    oneToOneOptional: User | null
    oneToOneRequired: User
    _links?: {
        self: ApiNavigationLink
        manyToMany: ApiNavigationLink
        manyToOneOptional: ApiNavigationLink
        manyToOneRequired: ApiNavigationLink
        oneToMany: ApiNavigationLink
        oneToOneOptional: ApiNavigationLink
        oneToOneRequired: ApiNavigationLink
    }
}

/**
 * This type is used for data transfer. Each time we read an object of this domain type from a rest service,
 * this type will be returned.
 */
export interface RelTestEntityDto extends RelTestEntityBase {
    _links: {
        self: ApiNavigationLink
        manyToMany: ApiNavigationLink
        manyToOneOptional: ApiNavigationLink
        manyToOneRequired: ApiNavigationLink
        oneToMany: ApiNavigationLink
        oneToOneOptional: ApiNavigationLink
        oneToOneRequired: ApiNavigationLink
    }
}

/**
 * This type is the default type of choice in the frontend as it has an id (which can be added to the `RelTestEntityDto`
 * via `apiHelper#getObjectId`). Consequently, this type is used for fields that reference this type.
 */
export interface RelTestEntity extends RelTestEntityDto {
    id: number
}

/**
 * This type is used as a basis for the different variants of this domain type. It can be created in the frontend
 * (in order to store it to the backend, for example) as it does neither have mandatory `_links` nor `id`.
 */
export interface UserBase extends ApiBase {
    name: string
    contacts: Contact[]
    _links?: {
        self: ApiNavigationLink
        contacts: ApiNavigationLink
    }
}

/**
 * This type is used for data transfer. Each time we read an object of this domain type from a rest service,
 * this type will be returned.
 */
export interface UserDto extends UserBase {
    _links: {
        self: ApiNavigationLink
        contacts: ApiNavigationLink
    }
}

/**
 * This type is the default type of choice in the frontend as it has an id (which can be added to the `UserDto`
 * via `apiHelper#getObjectId`). Consequently, this type is used for fields that reference this type.
 */
export interface User extends UserDto {
    id: number
}

export interface EmbeddableTestEntity {
    embeddedLong: number
    embeddedNullableInt: number | null
    embeddedText: string
}

export interface OtherEmbeddableTestEntity {
    embeddedNullableText: string | null
    otherEmbeddedNullableInt: number | null
}

export interface ContactBaseProjection extends Contact {
    
}

export interface PrimitiveTestEntityBaseProjection extends PrimitiveTestEntity {
    
}

export interface UserBaseProjection extends User {
    
}

export interface AddressBaseProjection extends Address {
    
}

export interface ContactFull extends Contact {
    address: AddressBaseProjection | null
}

export interface RelTestEntityBaseProjection extends RelTestEntity {
    
}

export interface FullRelTestEntity extends RelTestEntity {
    embedded: EmbeddableTestEntity | null
    embeddedNullable: OtherEmbeddableTestEntity | null
    manyToMany: UserBaseProjection[]
    manyToOneOptional: UserBaseProjection | null
    manyToOneRequired: UserBaseProjection
    oneToMany: UserBaseProjection[]
    oneToOneOptional: UserBaseProjection | null
    oneToOneRequired: UserBaseProjection
}